### ISSUE TITLE
NPE in mortar-sample

### ISSUE THREAD

**Issue by runningcode** [square/mortar#149]
Repro steps:
Hit the `Friends` menu button twice and then hit back twice.
OR
Hit the `Friends` menu button three times and hit back once.
```
04-28 12:39:45.234  10782-10782/com.example.mortar E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.example.mortar, PID: 10782
    java.lang.NullPointerException: Attempt to invoke virtual method 'mortar.MortarScope mortar.MortarScope.findChild(java.lang.String)' on a null object reference
            at com.example.mortar.mortarscreen.ScreenScoper.getScreenScope(ScreenScoper.java:50)
            at com.example.mortar.mortarscreen.ScreenScoper.getScreenScope(ScreenScoper.java:29)
            at com.example.mortar.mortarflow.MortarContextFactory.setUpContext(MortarContextFactory.java:18)
            at flow.path.Path$ContextFactory.setUpContext(Path.java:128)
            at flow.path.PathContext.create(PathContext.java:69)
            at com.example.mortar.screen.SimplePathContainer.performTraversal(SimplePathContainer.java:64)
            at flow.path.PathContainer.executeTraversal(PathContainer.java:89)
            at com.example.mortar.screen.FramePathContainerView.dispatch(FramePathContainerView.java:65)
            at com.example.mortar.core.MortarDemoActivity.dispatch(MortarDemoActivity.java:78)
            at flow.Flow$PendingTraversal.dispatch(Flow.java:315)
            at flow.Flow$3.doExecute(Flow.java:220)
            at flow.Flow$PendingTraversal.execute(Flow.java:323)
            at flow.Flow.move(Flow.java:232)
            at flow.Flow.goBack(Flow.java:211)
            at com.example.mortar.screen.BackSupport.onBackPressed(BackSupport.java:33)
            at com.example.mortar.screen.FramePathContainerView.onBackPressed(FramePathContainerView.java:74)
            at com.example.mortar.core.MortarDemoActivity.onBackPressed(MortarDemoActivity.java:150)
            at android.app.Activity.onKeyUp(Activity.java:2456)
            at android.view.KeyEvent.dispatch(KeyEvent.java:2646)
            at android.app.Activity.dispatchKeyEvent(Activity.java:2707)
            at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchKeyEvent(PhoneWindow.java:2330)
            at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:4026)
            at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:3988)
            at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3550)
            at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3603)
            at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3569)
            at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3686)
            at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3577)
            at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3743)
            at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3550)
            at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3603)
            at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3569)
            at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3577)
            at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3550)
            at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3603)
            at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3569)
            at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3719)
            at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:3880)
            at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:2208)
            at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:1849)
            at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:1840)
            at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:2185)
            at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:141)
            at android.os.MessageQueue.nativePollOnce(Native Method)
            at android.os.MessageQueue.next(MessageQueue.java:143)
            at android.os.Looper.loop(Looper.java:122)
            at android.app.ActivityThread.main(ActivityThread.java:5293)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
```

**Comment by hijamoya** [comment]
I meet the same issue..

**Comment by pyricau** [comment]
PRs welcome!
