### ISSUE TITLE
Scope  was destroyed before onSaveInstanceState

### ISSUE THREAD

**Issue by niqo01** [square/mortar#87]
Do you have any idea on what could cause the activity scope to be destroyed before the same activity `performSaveInstanceState` is called?

Crash:

```
java.lang.IllegalStateException: Scope com.couchsurfing.mobile.ui.setup.SetupActivityBlueprint was destroyed
       at mortar.RealScope.assertNotDead(RealScope.java:150)
       at mortar.RealActivityScope.onSaveInstanceState(RealActivityScope.java:93)
       at com.couchsurfing.mobile.ui.base.BaseActivity.onSaveInstanceState(BaseActivity.java:100)
       at android.app.Activity.performSaveInstanceState(Activity.java:1152)
       at android.app.Instrumentation.callActivityOnSaveInstanceState(Instrumentation.java:1223)
       at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:3156)
       at android.app.ActivityThread.handleStopActivity(ActivityThread.java:3215)
       at android.app.ActivityThread.access$1000(ActivityThread.java:135)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1424)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:4998)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:777)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:593)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

**Comment by rjrjr** [comment]
Probably can avoid this mess by using `singleTask` or `singleInstance` launch mode. Should confirm that, or if it's not true bring this code to the sample.

**Comment by lklots** [comment]
FWIW singleTask and singleInstance cannot be relied on to solve this problem.

**Comment by Lakedaemon** [comment]
Including taskId fixed my espresso tests (they create and tear down activities/mortar scopes real fast and I ended up having dead MortarScopes)
